# syntax=docker/dockerfile:1
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copy .env file
COPY .env .env

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] 